# Netlify configuration file


[build]
  base = "cofounder-app"
  command = "npm run build" # Standard CRA build command
  publish = "build"         # Standard CRA output directory

# Environment variables should be set in the Netlify UI, not in netlify.toml for security and compatibility.

# Redirect rule for Single Page Applications (SPA)
# This ensures that direct navigation to routes like /dashboard or /login
# are handled by index.html so React Router can take over.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
